---
apiVersion: v1
kind: Namespace
metadata:
  name: websecure-external-secrets
  labels:
    name: websecure-external-secrets
    app.kubernetes.io/name: external-secrets
    app.kubernetes.io/component: namespace
